# Generated by Django 4.1.2 on 2023-01-30 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0017_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_user_like',
            field=models.ManyToManyField(related_name='art_user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comm_user_like',
            field=models.ManyToManyField(related_name='comm_user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
