# Generated by Django 4.1.2 on 2023-01-31 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0018_article_art_user_like_comment_comm_user_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_user_like',
            field=models.ManyToManyField(blank=True, related_name='art_user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comm_user_like',
            field=models.ManyToManyField(blank=True, related_name='comm_user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
