# Generated by Django 4.1.2 on 2023-01-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221223_1431'),
        ('webapp', '0019_alter_article_art_user_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='art_user_like',
        ),
        migrations.AddField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='accounts.profile'),
        ),
    ]
