# Generated by Django 4.1.2 on 2023-01-31 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0020_remove_article_art_user_like_article_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='liked',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
